### ISSUE TITLE
Suggestion: Add .clang-format indentation guide

### ISSUE THREAD

**Issue by NewProggie** [sftrabbit/CppSamples-Samples#34]
Hey,

besides modern C++ samples it's good practice to use a consistent style (especially if the code base is increasingly growing). Therefore I'd suggest a .clang-format file as an indendation guide such as:

```
# Clang-Format Style Options for 3.6+

---
BasedOnStyle: Google
IndentWidth: 4

---
Language: Cpp
# Extra indent/outdent of access modifiers, e.g. public:
AccessModifierOffset: -2
AllowShortBlocksOnASingleLine: true
NamespaceIndentation: All
Standard: Cpp11
```

**Comment by sftrabbit** [comment]
I'm trying to enforce a very flexible style guide on the samples (although of course all of the ones I've written have the same style). The reason for this is because I don't want to suggest that one particular style is the "most modern" or "most idiomatic" - it's really just personal preference. The only thing I really try to make consistent is the use of tabs for indentation and spaces for alignment. I might look into this at a later point.
