### ISSUE TITLE
Suggestion: linking contributor github profiles

### ISSUE THREAD

**Issue by ilpropheta** [sftrabbit/CppSamples-Samples#51]
On sample pages, is it possible to link each contributor icon to his/her github profile? 
E.g. here:
![snap](https://cloud.githubusercontent.com/assets/5806546/7381055/460e77be-ee00-11e4-9549-2620a8fb74d6.png)
It would be cool to have a link on the second (blank) icon!

**Comment by sftrabbit** [comment]
This has been fixed in the latest build. The previous solution would only work if the email in your commit was publicly associated with a GitHub account. Now we have a manually maintained contributors file which contains everybody's GitHub usernames. It'll still fall back to the old solution if the person is not found in the contributors file.

**Comment by ilpropheta** [comment]
Cool! You're doing a great work Joseph :+1:
