### ISSUE TITLE
Incorrect usage of unique_ptr in 1-common-tasks/classes/rule-of-zero.cpp

### ISSUE THREAD

**Issue by btolfa** [sftrabbit/CppSamples-Samples#6]
I think you shouldn't use unique_ptr for example with deep copy, because unique_ptr used for sole ownership of object.

**Comment by sftrabbit** [comment]
I believe this is correct. If we're performing deep copies, only one object will ever have ownership of that resource. If I'm missing something, please tell me!

**Comment by Fiona-J-W** [comment]
I think the best way to demonstrate what rule-of-zero is about is to create a class with a `std::vector<int>`, because that will provide all the required operations implicitly with the right semantics. The current example is IMHO a clear code-smell and undesirable. (Never share mutable state across several instances of the same class.)

**Comment by sftrabbit** [comment]
That's a good idea. I've been back and forth on how best to present the different rule of Ns. I think I've come to a good conclusion though:
- One sample demonstrating rule of zero
- One sample demonstrating rule of five, which uses the rule of three as a starting point, mentioning that move constructor/assignment is not strictly necessary but provides an optimisation in most cases
- One sample demonstrating how to make a class moveable (similar to previous, but description focusses more on move semantics)
